# Generated by Django 3.2.6 on 2021-09-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='USA', max_length=150, verbose_name='Страна'),
        ),
    ]
